version: '3.4'

services:
  paymais-api:
    image: paymaisapi
    build:
      context: ./
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 8000:8000
    volumes:
      - .:/app
      - /app/node_modules
  eventstoreService:
    container_name: eventstoreService
    ports:
      - "2113:2113"
      - "1113:1113"
    image: eventstore/eventstore:release-5.0.8
    labels:
      kompose.service.type: nodeport
      kompose.service.expose: "true"
      kompose.image-pull-policy: "Always"

  natsService:
    container_name: natsService
    ports:
      - "4222:4222"
      - "6222:6222"
      - "8222:8222"
    image: nats
    labels:
      kompose.service.type: nodeport
      kompose.service.expose: "true"
      kompose.image-pull-policy: "Always"
